### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by Magesh7803** [iKrishneel/octomap_server2#1]
Hi Sir,
I was build octomap_server2 package and i get the following errors...Couldn't understand why this error is being reported.
>>>>>>>>>>>>>>>>>>>>>>>>>
ros2@ros2-HP-EliteBook-850-G3:~/testoct_ws$ colcon build --symlink-install
Starting >>> pcl_msgs
Starting >>> octomap_msgs
Finished <<< octomap_msgs [3.98s]                                                                  
Finished <<< pcl_msgs [4.23s]                       
Starting >>> pcl_conversions
Finished <<< pcl_conversions [0.95s]                       
Starting >>> octomap_server2
Starting >>> perception_pcl                   
Finished <<< perception_pcl [0.71s]                                                             
--- stderr: octomap_server2                               
** WARNING ** io features related to ensenso will be disabled
** WARNING ** io features related to davidSDK will be disabled
** WARNING ** io features related to dssdk will be disabled
** WARNING ** io features related to pcap will be disabled
** WARNING ** io features related to png will be disabled
** WARNING ** io features related to libusb-1.0 will be disabled
** WARNING ** visualization features related to ensenso will be disabled
** WARNING ** visualization features related to davidSDK will be disabled
** WARNING ** visualization features related to dssdk will be disabled
** WARNING ** visualization features related to rssdk will be disabled
<command-line>:0:1: error: macro names must be identifiers
<command-line>:0:1: error: macro names must be identifiers
<command-line>:0:1: error: macro names must be identifiers
make[2]: *** [CMakeFiles/octomap_server2.dir/src/transforms.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [CMakeFiles/octomap_server2.dir/src/conversions.cpp.o] Error 1
In file included from /home/ros2/testoct_ws/octomap_server2/include/octomap_server2/octomap_server.hpp:24:0,
                 from /home/ros2/testoct_ws/octomap_server2/src/octomap_server.cpp:2:
/usr/include/pcl-1.8/pcl/sample_consensus/model_types.h: In function ‘void __static_initialization_and_destruction_0(int, int)’:
/usr/include/pcl-1.8/pcl/sample_consensus/model_types.h:99:3: warning: ‘pcl::SAC_SAMPLE_SIZE’ is deprecated: This map is deprecated and is kept only to prevent breaking existing user code. Starting from PCL 1.8.0 model sample size is a protected member of the SampleConsensusModel class [-Wdeprecated-declarations]
   SAC_SAMPLE_SIZE (sample_size_pairs, sample_size_pairs + sizeof (sample_size_pairs) / sizeof (SampleSizeModel));
   ^~~~~~~~~~~~~~~
/usr/include/pcl-1.8/pcl/sample_consensus/model_types.h:99:3: note: declared here
make[2]: *** [CMakeFiles/octomap_server2.dir/src/octomap_server.cpp.o] Error 1
make[1]: *** [CMakeFiles/octomap_server2.dir/all] Error 2
make: *** [all] Error 2
---
Failed   <<< octomap_server2 [23.6s, exited with code 2]

Summary: 4 packages finished [29.1s]
  1 package failed: octomap_server2
  1 package had stderr output: octomap_server2
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

Also pls find attached CMakeLists 

Thanks
Magesh

[CMakeLists.txt](https://github.com/iKrishneel/octomap_server2/files/5410412/CMakeLists.txt)

**Comment by iKrishneel** [comment]
Can you share the output of 
```bash
$ colcon build --symlink-install --packages-select octomap_server2 --event-handlers console_direct+
```

**Comment by Magesh7803** [comment]
Pls find the output

ros2@ros2-HP-EliteBook-850-G3:~/testoct_ws$ colcon build --symlink-install --packages-select octomap_server2 --event-handlers console_direct+
Starting >>> octomap_server2
[ 33%] Built target octomap_server                  
[ 50%] Building CXX object CMakeFiles/octomap_server2.dir/src/conversions.cpp.o
[ 66%] Building CXX object CMakeFiles/octomap_server2.dir/src/transforms.cpp.o
[ 83%] Building CXX object CMakeFiles/octomap_server2.dir/src/octomap_server.cpp.o
<command-line>:0:1: error: macro names must be identifiers
<command-line>:0:1: error: macro names must be identifiers
<command-line>:0:1: error: macro names must be identifiers
CMakeFiles/octomap_server2.dir/build.make:86: recipe for target 'CMakeFiles/octomap_server2.dir/src/transforms.cpp.o' failed
make[2]: *** [CMakeFiles/octomap_server2.dir/src/transforms.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/home/ros2/testoct_ws/octomap_server2/src/conversions.cpp: In function ‘void octomap::pointsOctomapToPointCloud2(const point3d_list&, sensor_msgs::msg::PointCloud2&)’:
/home/ros2/testoct_ws/octomap_server2/src/conversions.cpp:53:57: warning: unused parameter ‘points’ [-Wunused-parameter]
     void pointsOctomapToPointCloud2(const point3d_list& points,
                                                         ^~~~~~
make[2]: *** [CMakeFiles/octomap_server2.dir/src/conversions.cpp.o] Error 1
CMakeFiles/octomap_server2.dir/build.make:110: recipe for target 'CMakeFiles/octomap_server2.dir/src/conversions.cpp.o' failed
In file included from /home/ros2/testoct_ws/octomap_server2/src/octomap_server.cpp:2:0:
/home/ros2/testoct_ws/octomap_server2/include/octomap_server2/octomap_server.hpp: In member function ‘virtual void octomap_server::OctomapServer::handleNode(const iterator&)’:
/home/ros2/testoct_ws/octomap_server2/include/octomap_server2/octomap_server.hpp:209:58: warning: unused parameter ‘it’ [-Wunused-parameter]
         virtual void handleNode(const OcTreeT::iterator& it) {};
                                                          ^~
/home/ros2/testoct_ws/octomap_server2/include/octomap_server2/octomap_server.hpp: In member function ‘virtual void octomap_server::OctomapServer::handleNodeInBBX(const iterator&)’:
/home/ros2/testoct_ws/octomap_server2/include/octomap_server2/octomap_server.hpp:210:63: warning: unused parameter ‘it’ [-Wunused-parameter]
         virtual void handleNodeInBBX(const OcTreeT::iterator& it) {};
                                                               ^~
/home/ros2/testoct_ws/octomap_server2/include/octomap_server2/octomap_server.hpp: In constructor ‘octomap_server::OctomapServer::OctomapServer(const rclcpp::NodeOptions&, std::__cxx11::string)’:
/home/ros2/testoct_ws/octomap_server2/include/octomap_server2/octomap_server.hpp:147:14: warning: ‘octomap_server::OctomapServer::m_useColoredMap’ will be initialized after [-Wreorder]
         bool m_useColoredMap;
              ^~~~~~~~~~~~~~~
/home/ros2/testoct_ws/octomap_server2/include/octomap_server2/octomap_server.hpp:117:16: warning:   ‘double octomap_server::OctomapServer::m_colorFactor’ [-Wreorder]
         double m_colorFactor;
                ^~~~~~~~~~~~~
/home/ros2/testoct_ws/octomap_server2/src/octomap_server.cpp:5:5: warning:   when initialized here [-Wreorder]
     OctomapServer::OctomapServer(
     ^~~~~~~~~~~~~
/home/ros2/testoct_ws/octomap_server2/src/octomap_server.cpp: In member function ‘virtual void octomap_server::OctomapServer::publishAll(const rclcpp::Time&)’:
/home/ros2/testoct_ws/octomap_server2/src/octomap_server.cpp:596:28: warning: unused variable ‘size’ [-Wunused-variable]
                     double size = it.getSize();
                            ^~~~
/home/ros2/testoct_ws/octomap_server2/src/octomap_server.cpp: In member function ‘virtual bool octomap_server::OctomapServer::octomapBinarySrv(std::shared_ptr<octomap_msgs::srv::GetOctomap_Request_<std::allocator<void> > >, std::shared_ptr<octomap_msgs::srv::GetOctomap_Response_<std::allocator<void> > >)’:
/home/ros2/testoct_ws/octomap_server2/src/octomap_server.cpp:784:52: warning: unused parameter ‘req’ [-Wunused-parameter]
         const std::shared_ptr<OctomapSrv::Request> req,
                                                    ^~~
/home/ros2/testoct_ws/octomap_server2/src/octomap_server.cpp: In member function ‘virtual bool octomap_server::OctomapServer::octomapFullSrv(std::shared_ptr<octomap_msgs::srv::GetOctomap_Request_<std::allocator<void> > >, std::shared_ptr<octomap_msgs::srv::GetOctomap_Response_<std::allocator<void> > >)’:
/home/ros2/testoct_ws/octomap_server2/src/octomap_server.cpp:803:52: warning: unused parameter ‘req’ [-Wunused-parameter]
         const std::shared_ptr<OctomapSrv::Request> req,
                                                    ^~~
/home/ros2/testoct_ws/octomap_server2/src/octomap_server.cpp: In member function ‘bool octomap_server::OctomapServer::clearBBXSrv(std::shared_ptr<octomap_msgs::srv::BoundingBoxQuery_Request_<std::allocator<void> > >, std::shared_ptr<octomap_msgs::srv::BoundingBoxQuery_Response_<std::allocator<void> > >)’:
/home/ros2/testoct_ws/octomap_server2/src/octomap_server.cpp:818:43: warning: unused parameter ‘resp’ [-Wunused-parameter]
         std::shared_ptr<BBXSrv::Response> resp) {
                                           ^~~~
/home/ros2/testoct_ws/octomap_server2/src/octomap_server.cpp: In member function ‘bool octomap_server::OctomapServer::resetSrv(std::shared_ptr<std_srvs::srv::Empty_Request_<std::allocator<void> > >, std::shared_ptr<std_srvs::srv::Empty_Response_<std::allocator<void> > >)’:
/home/ros2/testoct_ws/octomap_server2/src/octomap_server.cpp:856:28: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for (auto i = 0; i < occupiedNodesVis.markers.size(); ++i){
                          ~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/ros2/testoct_ws/octomap_server2/src/octomap_server.cpp:872:28: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for (auto i = 0; i < freeNodesVis.markers.size(); ++i) {
                          ~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/ros2/testoct_ws/octomap_server2/src/octomap_server.cpp:836:62: warning: unused parameter ‘req’ [-Wunused-parameter]
         const std::shared_ptr<std_srvs::srv::Empty::Request> req,
                                                              ^~~
/home/ros2/testoct_ws/octomap_server2/src/octomap_server.cpp:837:57: warning: unused parameter ‘resp’ [-Wunused-parameter]
         std::shared_ptr<std_srvs::srv::Empty::Response> resp) {
                                                         ^~~~
/home/ros2/testoct_ws/octomap_server2/src/octomap_server.cpp: In member function ‘virtual void octomap_server::OctomapServer::handlePreNodeTraversal(const rclcpp::Time&)’:
/home/ros2/testoct_ws/octomap_server2/src/octomap_server.cpp:1164:59: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
                 for (unsigned int j = mapUpdateBBXMinY; j <= mapUpdateBBXMaxY; ++j) {
                                                         ~~^~~~~~~~~~~~~~~~~~~
/home/ros2/testoct_ws/octomap_server2/src/octomap_server.cpp: In member function ‘virtual void octomap_server::OctomapServer::handlePostNodeTraversal(const rclcpp::Time&)’:
/home/ros2/testoct_ws/octomap_server2/src/octomap_server.cpp:1174:29: warning: unused parameter ‘rostime’ [-Wunused-parameter]
         const rclcpp::Time& rostime){
                             ^~~~~~~
In file included from /home/ros2/testoct_ws/octomap_server2/include/octomap_server2/octomap_server.hpp:24:0,
                 from /home/ros2/testoct_ws/octomap_server2/src/octomap_server.cpp:2:
/usr/include/pcl-1.8/pcl/sample_consensus/model_types.h: In function ‘void __static_initialization_and_destruction_0(int, int)’:
/usr/include/pcl-1.8/pcl/sample_consensus/model_types.h:99:3: warning: ‘pcl::SAC_SAMPLE_SIZE’ is deprecated: This map is deprecated and is kept only to prevent breaking existing user code. Starting from PCL 1.8.0 model sample size is a protected member of the SampleConsensusModel class [-Wdeprecated-declarations]
   SAC_SAMPLE_SIZE (sample_size_pairs, sample_size_pairs + sizeof (sample_size_pairs) / sizeof (SampleSizeModel));
   ^~~~~~~~~~~~~~~
/usr/include/pcl-1.8/pcl/sample_consensus/model_types.h:99:3: note: declared here
make[2]: *** [CMakeFiles/octomap_server2.dir/src/octomap_server.cpp.o] Error 1
CMakeFiles/octomap_server2.dir/build.make:62: recipe for target 'CMakeFiles/octomap_server2.dir/src/octomap_server.cpp.o' failed
CMakeFiles/Makefile2:131: recipe for target 'CMakeFiles/octomap_server2.dir/all' failed
make[1]: *** [CMakeFiles/octomap_server2.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
--- stderr: octomap_server2                               
<command-line>:0:1: error: macro names must be identifiers
<command-line>:0:1: error: macro names must be identifiers
<command-line>:0:1: error: macro names must be identifiers
make[2]: *** [CMakeFiles/octomap_server2.dir/src/transforms.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/home/ros2/testoct_ws/octomap_server2/src/conversions.cpp: In function ‘void octomap::pointsOctomapToPointCloud2(const point3d_list&, sensor_msgs::msg::PointCloud2&)’:
/home/ros2/testoct_ws/octomap_server2/src/conversions.cpp:53:57: warning: unused parameter ‘points’ [-Wunused-parameter]
     void pointsOctomapToPointCloud2(const point3d_list& points,
                                                         ^~~~~~
make[2]: *** [CMakeFiles/octomap_server2.dir/src/conversions.cpp.o] Error 1
In file included from /home/ros2/testoct_ws/octomap_server2/src/octomap_server.cpp:2:0:
/home/ros2/testoct_ws/octomap_server2/include/octomap_server2/octomap_server.hpp: In member function ‘virtual void octomap_server::OctomapServer::handleNode(const iterator&)’:
/home/ros2/testoct_ws/octomap_server2/include/octomap_server2/octomap_server.hpp:209:58: warning: unused parameter ‘it’ [-Wunused-parameter]
         virtual void handleNode(const OcTreeT::iterator& it) {};
                                                          ^~
/home/ros2/testoct_ws/octomap_server2/include/octomap_server2/octomap_server.hpp: In member function ‘virtual void octomap_server::OctomapServer::handleNodeInBBX(const iterator&)’:
/home/ros2/testoct_ws/octomap_server2/include/octomap_server2/octomap_server.hpp:210:63: warning: unused parameter ‘it’ [-Wunused-parameter]
         virtual void handleNodeInBBX(const OcTreeT::iterator& it) {};
                                                               ^~
/home/ros2/testoct_ws/octomap_server2/include/octomap_server2/octomap_server.hpp: In constructor ‘octomap_server::OctomapServer::OctomapServer(const rclcpp::NodeOptions&, std::__cxx11::string)’:
/home/ros2/testoct_ws/octomap_server2/include/octomap_server2/octomap_server.hpp:147:14: warning: ‘octomap_server::OctomapServer::m_useColoredMap’ will be initialized after [-Wreorder]
         bool m_useColoredMap;
              ^~~~~~~~~~~~~~~
/home/ros2/testoct_ws/octomap_server2/include/octomap_server2/octomap_server.hpp:117:16: warning:   ‘double octomap_server::OctomapServer::m_colorFactor’ [-Wreorder]
         double m_colorFactor;
                ^~~~~~~~~~~~~
/home/ros2/testoct_ws/octomap_server2/src/octomap_server.cpp:5:5: warning:   when initialized here [-Wreorder]
     OctomapServer::OctomapServer(
     ^~~~~~~~~~~~~
/home/ros2/testoct_ws/octomap_server2/src/octomap_server.cpp: In member function ‘virtual void octomap_server::OctomapServer::publishAll(const rclcpp::Time&)’:
/home/ros2/testoct_ws/octomap_server2/src/octomap_server.cpp:596:28: warning: unused variable ‘size’ [-Wunused-variable]
                     double size = it.getSize();
                            ^~~~
/home/ros2/testoct_ws/octomap_server2/src/octomap_server.cpp: In member function ‘virtual bool octomap_server::OctomapServer::octomapBinarySrv(std::shared_ptr<octomap_msgs::srv::GetOctomap_Request_<std::allocator<void> > >, std::shared_ptr<octomap_msgs::srv::GetOctomap_Response_<std::allocator<void> > >)’:
/home/ros2/testoct_ws/octomap_server2/src/octomap_server.cpp:784:52: warning: unused parameter ‘req’ [-Wunused-parameter]
         const std::shared_ptr<OctomapSrv::Request> req,
                                                    ^~~
/home/ros2/testoct_ws/octomap_server2/src/octomap_server.cpp: In member function ‘virtual bool octomap_server::OctomapServer::octomapFullSrv(std::shared_ptr<octomap_msgs::srv::GetOctomap_Request_<std::allocator<void> > >, std::shared_ptr<octomap_msgs::srv::GetOctomap_Response_<std::allocator<void> > >)’:
/home/ros2/testoct_ws/octomap_server2/src/octomap_server.cpp:803:52: warning: unused parameter ‘req’ [-Wunused-parameter]
         const std::shared_ptr<OctomapSrv::Request> req,
                                                    ^~~
/home/ros2/testoct_ws/octomap_server2/src/octomap_server.cpp: In member function ‘bool octomap_server::OctomapServer::clearBBXSrv(std::shared_ptr<octomap_msgs::srv::BoundingBoxQuery_Request_<std::allocator<void> > >, std::shared_ptr<octomap_msgs::srv::BoundingBoxQuery_Response_<std::allocator<void> > >)’:
/home/ros2/testoct_ws/octomap_server2/src/octomap_server.cpp:818:43: warning: unused parameter ‘resp’ [-Wunused-parameter]
         std::shared_ptr<BBXSrv::Response> resp) {
                                           ^~~~
/home/ros2/testoct_ws/octomap_server2/src/octomap_server.cpp: In member function ‘bool octomap_server::OctomapServer::resetSrv(std::shared_ptr<std_srvs::srv::Empty_Request_<std::allocator<void> > >, std::shared_ptr<std_srvs::srv::Empty_Response_<std::allocator<void> > >)’:
/home/ros2/testoct_ws/octomap_server2/src/octomap_server.cpp:856:28: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for (auto i = 0; i < occupiedNodesVis.markers.size(); ++i){
                          ~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/ros2/testoct_ws/octomap_server2/src/octomap_server.cpp:872:28: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for (auto i = 0; i < freeNodesVis.markers.size(); ++i) {
                          ~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/ros2/testoct_ws/octomap_server2/src/octomap_server.cpp:836:62: warning: unused parameter ‘req’ [-Wunused-parameter]
         const std::shared_ptr<std_srvs::srv::Empty::Request> req,
                                                              ^~~
/home/ros2/testoct_ws/octomap_server2/src/octomap_server.cpp:837:57: warning: unused parameter ‘resp’ [-Wunused-parameter]
         std::shared_ptr<std_srvs::srv::Empty::Response> resp) {
                                                         ^~~~
/home/ros2/testoct_ws/octomap_server2/src/octomap_server.cpp: In member function ‘virtual void octomap_server::OctomapServer::handlePreNodeTraversal(const rclcpp::Time&)’:
/home/ros2/testoct_ws/octomap_server2/src/octomap_server.cpp:1164:59: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
                 for (unsigned int j = mapUpdateBBXMinY; j <= mapUpdateBBXMaxY; ++j) {
                                                         ~~^~~~~~~~~~~~~~~~~~~
/home/ros2/testoct_ws/octomap_server2/src/octomap_server.cpp: In member function ‘virtual void octomap_server::OctomapServer::handlePostNodeTraversal(const rclcpp::Time&)’:
/home/ros2/testoct_ws/octomap_server2/src/octomap_server.cpp:1174:29: warning: unused parameter ‘rostime’ [-Wunused-parameter]
         const rclcpp::Time& rostime){
                             ^~~~~~~
In file included from /home/ros2/testoct_ws/octomap_server2/include/octomap_server2/octomap_server.hpp:24:0,
                 from /home/ros2/testoct_ws/octomap_server2/src/octomap_server.cpp:2:
/usr/include/pcl-1.8/pcl/sample_consensus/model_types.h: In function ‘void __static_initialization_and_destruction_0(int, int)’:
/usr/include/pcl-1.8/pcl/sample_consensus/model_types.h:99:3: warning: ‘pcl::SAC_SAMPLE_SIZE’ is deprecated: This map is deprecated and is kept only to prevent breaking existing user code. Starting from PCL 1.8.0 model sample size is a protected member of the SampleConsensusModel class [-Wdeprecated-declarations]
   SAC_SAMPLE_SIZE (sample_size_pairs, sample_size_pairs + sizeof (sample_size_pairs) / sizeof (SampleSizeModel));
   ^~~~~~~~~~~~~~~
/usr/include/pcl-1.8/pcl/sample_consensus/model_types.h:99:3: note: declared here
make[2]: *** [CMakeFiles/octomap_server2.dir/src/octomap_server.cpp.o] Error 1
make[1]: *** [CMakeFiles/octomap_server2.dir/all] Error 2
make: *** [all] Error 2
---
Failed   <<< octomap_server2 [19.6s, exited with code 2]

Summary: 0 packages finished [19.9s]
  1 package failed: octomap_server2
  1 package had stderr output: octomap_server2
ros2@ros2-HP-EliteBook-850-G3:~/testoct_ws$

**Comment by iKrishneel** [comment]
Can you try installing by following this [script](https://github.com/iKrishneel/octomap_server2/blob/master/.github/travis.sh) and see if it gives the same error?

**Comment by Magesh7803** [comment]
I tried the steps mentioned in the script...but no success . I get the same error. Also, pls note i have done foxy installation from source.

**Comment by iKrishneel** [comment]
Try upgrading `pcl`

**Comment by Magesh7803** [comment]
Hi Sir,
Upgrading pcl to the latest version pcl-1.11 solved the issue...Thanks a ton.
